apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: blog
    tier: backend
spec:
  selector:
    app: blog
    tier: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: blog
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
      tier: backend
  template:
    metadata:
      labels:
        app: blog
        tier: backend
    spec:
      containers:
        - name: blog-backend
          image: 776060341642.dkr.ecr.us-east-1.amazonaws.com/blog-tech-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@db:5432/blog