apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: blog
    tier: database
spec:
  selector:
    app: blog
    tier: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: blog
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
      tier: database
  template:
    metadata:
      labels:
        app: blog
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: blog
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres