# .github/workflows/deploy_to_eks.yml
name: Deploy to EKS Cluster

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1 # Confirme que esta é a região do seu EKS

jobs:
  deploy-to-eks:
    name: Apply Kubernetes Manifests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Essencial para o AWS OIDC e autenticação com EKS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using Access Keys
        uses: aws-actions/configure-aws-credentials@v4 # Configura as credenciais AWS
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3 # Instala ou garante que o kubectl está disponível

      - name: Configure kubeconfig for EKS via AWS CLI
        run: |
          # O AWS CLI já está pré-instalado na maioria dos runners do GitHub Actions.
          # Este comando configura o kubectl para se comunicar com o seu cluster EKS.
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name opm-prod # <--- SUBSTITUA 'opm-prod' SE O NOME DO CLUSTER FOR OUTRO!
          echo "✅ Kubeconfig configurado para o cluster opm-prod." # Mensagem de confirmação

      - name: Apply Kubernetes DB Deployment
        run: |
          kubectl apply -f db-deployment.yaml
          echo "✅ db-deployment.yaml aplicado."

      - name: Apply Kubernetes Backend Deployment
        run: |
          kubectl apply -f backend-deployment.yaml
          echo "✅ backend-deployment.yaml aplicado."